### PR TITLE
[11.0] Compute_res_fields return false

### PR DESCRIPTION
**Pull request by lieblinger**
The _compute_res_fields function in main formio_form model always returns false in sub modules (partner, crm and ...).

This returns to a not appropriated res_partner_id or crm_lead_id.

A fix could be my commit 2f0ea5b. Maybe there's a better solution.

### CODE REVIEW

**Comment by bobslee** [comment]
hi @lieblinger, I guess you mingled your Git branches.
This PR contains lots of Flectra related code. So I can't accept/merge.

**Comment by lieblinger** [comment]
That's ture.... The last commit doesn't belong in this repo.

What do you think about commit b5b1a21? There's no security testing. Your approach was checking for the formio.form model. I basically removed it and now it's only checking for the corresponding model (ex. res.partner).

**Comment by bobslee** [comment]
> What do you think about commit b5b1a21? There's no security testing. 

What do you mean with **"no security testing"**?

The commit b5b1a2153f273df547ed0ecf6e993f0b692bcb3e contains lots of changes. 
It also revert my `@api.depends` and other ones.
So sorry, ATM I can't accept this PR.

**Comment by lieblinger** [comment]
Okay, I'm gonna recreate it.

But could you confirm that what I did is right? I basically deleted the following:
```
if self._context.get('active_model') == 'formio.form':
            return True
        else:
            return False
```
Cause it always returned false in submodels (res.partner, sale.order and ...). This caused that for example the `res_partner_id` in sale.order extension equals NULL.

By checking with:
```if self._context.get('active_model') == 'crm.lead':```

for the model the rest of the code block gets executed and res_fields are filled with informations.

**Comment by lieblinger** [comment]
Sorry, I mixed up my flectra branch with 11.0.

I'll create an issue and then we'll talk there about it.

**Comment by bobslee** [comment]
Yesterday I worked in this part. Please wait with your changes.
I changed the way the `res` (resource) fields get their values assigned. Was a small but nice change.
I thoroughly tested with all modules, and works for v12. Still need to port and test v11.
Maybe I'm able to push my changes today.

**Comment by lieblinger** [comment]
This commit fixed the issue:
https://github.com/novacode-nl/odoo-formio/commit/ef0ece94f42e7a1acdc4ee69c4a5f559c76b54d7

Thanks!

**Comment by bobslee** [comment]
Your welcome, but that change wasn't enough.
I still ran into troubles when several formio specific modules installed e.g. formio_crm and formio_sale.

My current change should address this. But it's not pushed yet.

**Comment by bobslee** [comment]
Sorry, can't remember now whether I changed the super call. Texting this from my phone ;)

**Comment by lieblinger** [comment]
I've tested right now and I think it doesn't work without this:
https://github.com/novacode-nl/odoo-formio/blob/71954eeb8d9f65265f3974edb0e27af6e11be5ae/formio_crm/models/formio_form.py#L18

Your last commit removed this. If I'm adding this on submodules

`super(Form, self)._compute_res_fields()
`

All _compute_res_fields(self) gets called and it seems to be working on first view.

**Comment by bobslee** [comment]
Hi @lieblinger , I just pushed changes to v11 and v12 branches.
Please could you test/review if all form creations (with resource fields) now work properly?
Let me know :)

**Comment by lieblinger** [comment]
Res_fields get's populated with the correct informations.

Everything seems to be working : )

**Comment by bobslee** [comment]
Awesome and thanks for your feedback!

**Pull request closed without merging**
