### PR TITLE
[FIX] Component not getting parent_id when inside datagrid

### PR DESCRIPTION
**Pull request by lieblinger**

### CODE REVIEW

**Comment by bobslee** [comment]
Your change works for the datagrid, also when it's inside a layout component.
I take a look if we can simplify the 3 times of for loop in that piece.

Do you know a columns component don't get a parent, or is this by design for layout components?
See screenshot.
(perhaps also other layout components)

image

**Comment by bobslee** [comment]
Ok, I simplified the loops.
I shall merge the PR and push my changes.

**Comment by bobslee** [comment]
@lieblinger  Done:
- Merged
- Pushed an improvement (simplification)
- Release version 0.3

**Comment by lieblinger** [comment]
```
Do you know a columns component don't get a parent, or is this by design for layout components?
```

All layout elements should get a parent. I'll do some testing and push a fix.

**Pull request merged**
